# Artificial Neural Network

### 1. Importing the libraries

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf
from sklearn.preprocessing import LabelEncoder
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix

In [2]:
tf.__version__

'1.14.0'

## 2. Data Preprocessing

#### 2.1.  Importing the dataset

In [3]:
dataset = pd.read_csv('../data/Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [4]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [5]:
print(y)

[1 0 1 ... 1 1 0]


#### 2.2. Encoding categorical data

Label Encoding the "Gender" column

In [6]:
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [7]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


One Hot Encoding the "Geography" column

In [8]:
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [9]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


#### 2.3. Feature Scaling

In [10]:
sc = StandardScaler()
X = sc.fit_transform(X)

/gpfs/user/u555116/brc01/aim00/.venv3/lib/python3.6/site-packages/sklearn/utils/validation.py:595: DataConversionWarning: Data with input dtype object was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
/gpfs/user/u555116/brc01/aim00/.venv3/lib/python3.6/site-packages/sklearn/utils/validation.py:595: DataConversionWarning: Data with input dtype object was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [11]:
print(X)

[[ 0.99720391 -0.57873591 -0.57380915 ...  0.64609167  0.97024255
   0.02188649]
 [-1.00280393 -0.57873591  1.74273971 ... -1.54776799  0.97024255
   0.21653375]
 [ 0.99720391 -0.57873591 -0.57380915 ...  0.64609167 -1.03067011
   0.2406869 ]
 ...
 [ 0.99720391 -0.57873591 -0.57380915 ... -1.54776799  0.97024255
  -1.00864308]
 [-1.00280393  1.72790383 -0.57380915 ...  0.64609167 -1.03067011
  -0.12523071]
 [ 0.99720391 -0.57873591 -0.57380915 ...  0.64609167 -1.03067011
  -1.07636976]]


#### 2.3. Splitting the dataset into the Training set and Test set

In [12]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

## 3. Building the ANN

#### 3.1. Initializing the ANN

In [13]:
ann = tf.keras.models.Sequential()

#### 3.2. Adding the input layer and the first hidden layer

In [14]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

W0505 12:41:11.027482 140296187451200 deprecation.py:506] From /gpfs/user/u555116/brc01/aim00/.venv3/lib/python3.6/site-packages/tensorflow/python/ops/init_ops.py:1251: calling VarianceScaling.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


#### 3.3. Adding the second hidden layer

In [15]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

#### 3.4. Adding the output layer

In [16]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

## 4. Training the ANN

#### 4.1. Compiling the ANN

In [17]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

#### 4.2. Training the ANN on the Training set

In [18]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

W0505 12:41:13.595120 140296187451200 deprecation.py:323] From /gpfs/user/u555116/brc01/aim00/.venv3/lib/python3.6/site-packages/tensorflow/python/ops/nn_impl.py:180: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


Epoch 1/100
8000/8000 [==============================] - 0s 52us/sample - loss: 0.6352 - acc: 0.6881
Epoch 2/100
8000/8000 [==============================] - 0s 33us/sample - loss: 0.4771 - acc: 0.7960
Epoch 3/100
8000/8000 [==============================] - 0s 32us/sample - loss: 0.4430 - acc: 0.7979
Epoch 4/100
8000/8000 [==============================] - 0s 31us/sample - loss: 0.4262 - acc: 0.8101
Epoch 5/100
8000/8000 [==============================] - 0s 31us/sample - loss: 0.4135 - acc: 0.8217
Epoch 6/100
8000/8000 [==============================] - 0s 30us/sample - loss: 0.4024 - acc: 0.8265
Epoch 7/100
8000/8000 [==============================] - 0s 30us/sample - loss: 0.3897 - acc: 0.8364
Epoch 8/100
8000/8000 [==============================] - 0s 31us/sample - loss: 0.3770 - acc: 0.8445
Epoch 9/100
8000/8000 [==============================] - 0s 32us/sample - loss: 0.3674 - acc: 0.8495
Epoch 10/100
8000/8000 [==============================] - 0s 32us/sample - loss: 0.3603 - a

8000/8000 [==============================] - 0s 33us/sample - loss: 0.3305 - acc: 0.8649
Epoch 82/100
8000/8000 [==============================] - 0s 37us/sample - loss: 0.3308 - acc: 0.8641
Epoch 83/100
8000/8000 [==============================] - 0s 32us/sample - loss: 0.3307 - acc: 0.8645
Epoch 84/100
8000/8000 [==============================] - 0s 32us/sample - loss: 0.3308 - acc: 0.8666
Epoch 85/100
8000/8000 [==============================] - 0s 31us/sample - loss: 0.3304 - acc: 0.8649
Epoch 86/100
8000/8000 [==============================] - 0s 32us/sample - loss: 0.3305 - acc: 0.8648
Epoch 87/100
8000/8000 [==============================] - 0s 32us/sample - loss: 0.3302 - acc: 0.8656
Epoch 88/100
8000/8000 [==============================] - 0s 33us/sample - loss: 0.3305 - acc: 0.8645
Epoch 89/100
8000/8000 [==============================] - 0s 33us/sample - loss: 0.3303 - acc: 0.8640
Epoch 90/100
8000/8000 [==============================] - 0s 32us/sample - loss: 0.3306 - acc: 

## 5. Making the predictions and evaluating the model

#### 5.1. Predicting the Test set results

In [19]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


#### 5.2. Making the Confusion Matrix

In [20]:
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1509   86]
 [ 195  210]]
